# Generated by Django 5.0.3 on 2024-04-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_mes1', models.FloatField()),
                ('consumo_mes2', models.FloatField()),
                ('consumo_mes3', models.FloatField()),
                ('tarifa_distribuidora', models.FloatField()),
                ('tipo_tarifa', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('industrial', 'Industrial')], max_length=20)),
                ('economia_anual', models.FloatField(blank=True, null=True)),
                ('economia_mensal', models.FloatField(blank=True, null=True)),
                ('desconto_aplicado', models.FloatField(blank=True, null=True)),
                ('cobertura', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
