# Generated by Django 5.0.3 on 2024-04-06 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_consumer_consumptionrules_delete_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='ConsumptionRule',
        ),
        migrations.AddField(
            model_name='consumer',
            name='consumption_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.consumptionrules', verbose_name='Regra de Desconto'),
        ),
        migrations.AlterField(
            model_name='consumptionrules',
            name='discount',
            field=models.IntegerField(verbose_name='valor_com_desconto'),
        ),
    ]
