# Generated by Django 5.0.3 on 2024-04-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_consumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_range', models.CharField(max_length=50, verbose_name='Faixa de Consumo')),
                ('consumer_type', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], max_length=20, verbose_name='Tipo de Consumidor')),
                ('cover_value', models.FloatField(verbose_name='Valor da Cobertura')),
                ('discount_value', models.FloatField(verbose_name='Valor do Desconto (%)')),
            ],
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
    ]
