# Generated by Django 5.0.3 on 2024-04-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_consumer_consumptionrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrules',
            name='consumer_type',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('industrial', 'Industrial')], default=1, max_length=20, verbose_name='Tipo de Consumidor'),
            preserve_default=False,
        ),
    ]
