# Generated by Django 5.0.4 on 2024-04-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_discountrules_cover_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountrules',
            name='consumption_range',
            field=models.FloatField(verbose_name='consumo (kwh)'),
        ),
        migrations.AlterField(
            model_name='discountrules',
            name='cover',
            field=models.FloatField(verbose_name='cobertura %'),
        ),
        migrations.AlterField(
            model_name='discountrules',
            name='discount',
            field=models.IntegerField(verbose_name='valor_com_desconto %'),
        ),
    ]
